[package]
name = "pc-finder"
version = "0.1.0"
authors = ["MinusKelvin <mark.carlson@minuskelvin.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
criterion = "0.3"
fumen = { git = "https://github.com/MinusKelvin/fumen-rs" }

[[bench]]
name = "combination"
harness = false